CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "LogsAuditoria" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Timestamp" timestamp with time zone NOT NULL,
    "UsuarioId" integer NOT NULL,
    "UsuarioEmail" text NOT NULL,
    "Acao" text NOT NULL,
    "Detalhes" text NOT NULL,
    CONSTRAINT "PK_LogsAuditoria" PRIMARY KEY ("Id")
);

CREATE TABLE "Perfis" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    CONSTRAINT "PK_Perfis" PRIMARY KEY ("Id")
);

CREATE TABLE "Usuarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" text NOT NULL,
    "Nome" text NOT NULL,
    "Email" text NOT NULL,
    "SenhaHash" text NOT NULL,
    "PerfilId" integer NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Usuarios_Perfis_PerfilId" FOREIGN KEY ("PerfilId") REFERENCES "Perfis" ("Id") ON DELETE CASCADE
);

CREATE TABLE "FinanceiroProdutor" (
    "FinanceiroId" integer NOT NULL,
    "ProdutorId" integer NOT NULL,
    CONSTRAINT "PK_FinanceiroProdutor" PRIMARY KEY ("FinanceiroId", "ProdutorId"),
    CONSTRAINT "FK_FinanceiroProdutor_Usuarios_FinanceiroId" FOREIGN KEY ("FinanceiroId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_FinanceiroProdutor_Usuarios_ProdutorId" FOREIGN KEY ("ProdutorId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Granjas" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" text NOT NULL,
    "Nome" text NOT NULL,
    "Localizacao" text,
    "UsuarioId" integer NOT NULL,
    CONSTRAINT "PK_Granjas" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Granjas_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Lotes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Codigo" text NOT NULL,
    "Identificador" text NOT NULL,
    "DataEntrada" timestamp with time zone NOT NULL,
    "DataSaida" timestamp with time zone,
    "QuantidadeAvesInicial" integer NOT NULL,
    "GranjaId" integer NOT NULL,
    CONSTRAINT "PK_Lotes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Lotes_Granjas_GranjaId" FOREIGN KEY ("GranjaId") REFERENCES "Granjas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Produtos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nome" text NOT NULL,
    "Tipo" text NOT NULL,
    "Quantidade" numeric NOT NULL,
    "UnidadeDeMedida" text NOT NULL,
    "GranjaId" integer NOT NULL,
    CONSTRAINT "PK_Produtos" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Produtos_Granjas_GranjaId" FOREIGN KEY ("GranjaId") REFERENCES "Granjas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TransacoesFinanceiras" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Descricao" text NOT NULL,
    "Valor" numeric NOT NULL,
    "Tipo" text NOT NULL,
    "Data" timestamp with time zone NOT NULL,
    "TimestampCriacao" timestamp with time zone NOT NULL,
    "UsuarioId" integer NOT NULL,
    "LoteId" integer,
    CONSTRAINT "PK_TransacoesFinanceiras" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TransacoesFinanceiras_Lotes_LoteId" FOREIGN KEY ("LoteId") REFERENCES "Lotes" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_TransacoesFinanceiras_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

INSERT INTO "Perfis" ("Id", "Nome")
VALUES (1, 'Administrador');
INSERT INTO "Perfis" ("Id", "Nome")
VALUES (2, 'Produtor');
INSERT INTO "Perfis" ("Id", "Nome")
VALUES (3, 'Financeiro');

INSERT INTO "Usuarios" ("Id", "Codigo", "Email", "Nome", "PerfilId", "SenhaHash")
VALUES (1, 'ADM-001', 'admin@admin.com', 'Admin Padrão', 1, '$2a$11$Y.7g.3s5B5B5B5B5B5B5B.u5n5n5n5n5n5n5n5n5n5n5n5n5n5n5n5');

CREATE INDEX "IX_FinanceiroProdutor_ProdutorId" ON "FinanceiroProdutor" ("ProdutorId");

CREATE INDEX "IX_Granjas_UsuarioId" ON "Granjas" ("UsuarioId");

CREATE INDEX "IX_Lotes_GranjaId" ON "Lotes" ("GranjaId");

CREATE INDEX "IX_Produtos_GranjaId" ON "Produtos" ("GranjaId");

CREATE INDEX "IX_TransacoesFinanceiras_LoteId" ON "TransacoesFinanceiras" ("LoteId");

CREATE INDEX "IX_TransacoesFinanceiras_UsuarioId" ON "TransacoesFinanceiras" ("UsuarioId");

CREATE INDEX "IX_Usuarios_PerfilId" ON "Usuarios" ("PerfilId");

SELECT setval(
    pg_get_serial_sequence('"Perfis"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Perfis") + 1,
        nextval(pg_get_serial_sequence('"Perfis"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Usuarios"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Usuarios") + 1,
        nextval(pg_get_serial_sequence('"Usuarios"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250820194048_InitialCreate', '9.0.8');

CREATE TABLE "Sensores" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Tipo" text NOT NULL,
    "IdentificadorUnico" text NOT NULL,
    "GranjaId" integer NOT NULL,
    CONSTRAINT "PK_Sensores" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Sensores_Granjas_GranjaId" FOREIGN KEY ("GranjaId") REFERENCES "Granjas" ("Id") ON DELETE CASCADE
);

CREATE TABLE "LeiturasSensores" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Valor" numeric NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "SensorId" integer NOT NULL,
    CONSTRAINT "PK_LeiturasSensores" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_LeiturasSensores_Sensores_SensorId" FOREIGN KEY ("SensorId") REFERENCES "Sensores" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_LeiturasSensores_SensorId" ON "LeiturasSensores" ("SensorId");

CREATE INDEX "IX_Sensores_GranjaId" ON "Sensores" ("GranjaId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250820231920_AddSensorEntities', '9.0.8');

ALTER TABLE "Lotes" ALTER COLUMN "Identificador" TYPE character varying(100);

ALTER TABLE "Lotes" ALTER COLUMN "Codigo" TYPE character varying(50);

ALTER TABLE "Lotes" ADD "AreaGalpao" numeric;

ALTER TABLE "Lotes" ADD "DataAbatePrevista" timestamp with time zone;

ALTER TABLE "Lotes" ADD "DataAtualizacao" timestamp with time zone;

ALTER TABLE "Lotes" ADD "DataCriacao" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';

ALTER TABLE "Lotes" ADD "Linhagem" character varying(100);

ALTER TABLE "Lotes" ADD "Observacoes" character varying(1000);

ALTER TABLE "Lotes" ADD "OrigemPintinhos" character varying(200);

ALTER TABLE "Lotes" ADD "QuantidadeAvesAtual" integer NOT NULL DEFAULT 0;

ALTER TABLE "Lotes" ADD "Status" character varying(50) NOT NULL DEFAULT '';

CREATE TABLE "ConsumosAgua" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LoteId" integer NOT NULL,
    "Data" timestamp with time zone NOT NULL,
    "QuantidadeLitros" numeric(10,3) NOT NULL,
    "AvesVivas" integer NOT NULL,
    "TemperaturaAmbiente" numeric,
    "Observacoes" character varying(500),
    "DataCriacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ConsumosAgua" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ConsumosAgua_Lotes_LoteId" FOREIGN KEY ("LoteId") REFERENCES "Lotes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ConsumosRacao" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LoteId" integer NOT NULL,
    "Data" timestamp with time zone NOT NULL,
    "QuantidadeKg" numeric(10,3) NOT NULL,
    "TipoRacao" character varying(50) NOT NULL,
    "AvesVivas" integer NOT NULL,
    "Observacoes" character varying(500),
    "DataCriacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ConsumosRacao" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ConsumosRacao_Lotes_LoteId" FOREIGN KEY ("LoteId") REFERENCES "Lotes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "EventosSanitarios" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LoteId" integer NOT NULL,
    "Data" timestamp with time zone NOT NULL,
    "TipoEvento" character varying(50) NOT NULL,
    "Produto" character varying(200) NOT NULL,
    "LoteProduto" character varying(100),
    "Dosagem" character varying(100),
    "ViaAdministracao" character varying(50),
    "AvesTratadas" integer,
    "DuracaoTratamentoDias" integer,
    "PeriodoCarenciaDias" integer,
    "ResponsavelAplicacao" character varying(200),
    "Sintomas" character varying(1000),
    "Observacoes" character varying(1000),
    "Custo" numeric,
    "DataCriacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_EventosSanitarios" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EventosSanitarios_Lotes_LoteId" FOREIGN KEY ("LoteId") REFERENCES "Lotes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "MedicoesQualidadeAr" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LoteId" integer NOT NULL,
    "DataHora" timestamp with time zone NOT NULL,
    "NH3_ppm" numeric(6,2),
    "CO2_ppm" numeric(8,2),
    "O2_percentual" numeric,
    "VelocidadeAr_ms" numeric,
    "Luminosidade_lux" numeric,
    "TemperaturaAr" numeric,
    "UmidadeRelativa" numeric,
    "LocalMedicao" character varying(100),
    "EquipamentoMedicao" character varying(200),
    "Observacoes" character varying(500),
    "DataCriacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_MedicoesQualidadeAr" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MedicoesQualidadeAr_Lotes_LoteId" FOREIGN KEY ("LoteId") REFERENCES "Lotes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "PesagensSemanais" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LoteId" integer NOT NULL,
    "DataPesagem" timestamp with time zone NOT NULL,
    "IdadeDias" integer NOT NULL,
    "SemanaVida" integer NOT NULL,
    "PesoMedioGramas" numeric(8,2) NOT NULL,
    "QuantidadeAmostrada" integer NOT NULL,
    "PesoMinimo" numeric,
    "PesoMaximo" numeric,
    "DesvioPadrao" numeric,
    "CoeficienteVariacao" numeric,
    "GanhoSemanal" numeric,
    "Observacoes" character varying(500),
    "DataCriacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PesagensSemanais" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PesagensSemanais_Lotes_LoteId" FOREIGN KEY ("LoteId") REFERENCES "Lotes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RegistrosAbate" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LoteId" integer NOT NULL,
    "DataAbate" timestamp with time zone NOT NULL,
    "DataAbatePrevista" timestamp with time zone,
    "IdadeAbateDias" integer NOT NULL,
    "QuantidadeEnviada" integer NOT NULL,
    "PesoVivoTotalKg" numeric(10,3) NOT NULL,
    "PesoCarcacaTotalKg" numeric,
    "AvesCondenadas" integer,
    "MotivoCondenacoes" character varying(1000),
    "PesoCondenadoKg" numeric,
    "FrigorificoDestino" character varying(200),
    "Transportadora" character varying(200),
    "ValorPorKg" numeric,
    "ValorTotalRecebido" numeric,
    "Observacoes" character varying(1000),
    "DataCriacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RegistrosAbate" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RegistrosAbate_Lotes_LoteId" FOREIGN KEY ("LoteId") REFERENCES "Lotes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RegistrosMortalidade" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "LoteId" integer NOT NULL,
    "Data" timestamp with time zone NOT NULL,
    "QuantidadeMortas" integer NOT NULL,
    "AvesVivas" integer NOT NULL,
    "CausaPrincipal" character varying(200),
    "IdadeDias" integer NOT NULL,
    "PesoMedioMortas" numeric,
    "Observacoes" character varying(1000),
    "AcaoTomada" character varying(500),
    "ResponsavelRegistro" character varying(200),
    "DataCriacao" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RegistrosMortalidade" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RegistrosMortalidade_Lotes_LoteId" FOREIGN KEY ("LoteId") REFERENCES "Lotes" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ConsumosAgua_LoteId_Data" ON "ConsumosAgua" ("LoteId", "Data");

CREATE INDEX "IX_ConsumosRacao_LoteId_Data" ON "ConsumosRacao" ("LoteId", "Data");

CREATE INDEX "IX_EventosSanitarios_LoteId" ON "EventosSanitarios" ("LoteId");

CREATE INDEX "IX_MedicoesQualidadeAr_LoteId" ON "MedicoesQualidadeAr" ("LoteId");

CREATE INDEX "IX_PesagensSemanais_LoteId_SemanaVida" ON "PesagensSemanais" ("LoteId", "SemanaVida");

CREATE INDEX "IX_RegistrosAbate_LoteId" ON "RegistrosAbate" ("LoteId");

CREATE INDEX "IX_RegistrosMortalidade_LoteId_Data" ON "RegistrosMortalidade" ("LoteId", "Data");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250827200629_AviculturaExtensao', '9.0.8');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250828190517_DB', '9.0.8');

COMMIT;

