name: Azure Static Web Apps - GranjaTech

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      # IMPORTANTES: evitam que warnings do ESLint quebrem o build
      CI: false
      DISABLE_ESLINT_PLUGIN: true
      # URL da API em produção
      REACT_APP_API_URL: https://granjatech-backend-felipebianchini2006-abb3chdzfjfed6hz.brazilsouth-01.azurewebsites.net/api

    steps:
      - uses: actions/checkout@v4

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"             # caminho do app React
          api_location: ""                     # sem Functions
          output_location: "build"             # padrão do CRA
          # Força o build com CI=false (reforço extra além do env)
          app_build_command: "CI=false npm run build"